server:
  port:
   8080
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/restaurant?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
#    username: root
#    password: 0978477143
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:restaurant}
    username: ${DATABASE_NAME:root}
    password: ${DATABASE_PASSWORD:0978477143}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: api
jwt:
  expiration: 43200 #12 hours = 12 * 60 * 60
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=

logging:
  level:
    org:
      springframework:
        security: DEBUG

# application.yml
debug: true

